name: Build and Push POS-Merchant

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-push-test:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      IMAGE_NAME: ${{ secrets.DOCKER_REPO_PREFIX }}/pos-merchant
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (Test)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (Test)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  build-and-push-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      IMAGE_NAME: ${{ secrets.DOCKER_REPO_PREFIX_PROD }}/pos-merchant
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (Prod)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME_PROD }}
          password: ${{ secrets.DOCKER_PASSWORD_PROD }}

      - name: Build and push Docker image (Prod)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}